### ISSUE TITLE
How to convert crontab from utc to other timezone...?

### ISSUE THREAD

**Issue by aliscie** [Sonic0/cron-converter#1]
How to convert crontab from utc to other timezone...?

**Comment by Sonic0** [comment]
Hi @aliscie,
Sorry, but conversions from UTC to local timezone, or vice-versa, isn't the scope of this library.
I made a library (very ugly code, but it work), based on this, to convert from local to UTC timezone. Maybe could be simple coding some lines of code using it as an example.
