### ISSUE TITLE
next() can be in the past if the specified datetime is millseconds after the schedule time

### ISSUE THREAD

**Issue by PhracturedBlue** [Sonic0/cron-converter#5]
If I specify:
`Cron("* * * * *").schedule(datetime.datetime(2023, 1, 3, 15, 17, 0, 5)).next().isoformat()`
I get a response:
`2023-01-03T15:17:00`
I would have expected a response of:
`2023-01-03T15:17:01` since I expect the next() time to be greater than the current time

**Comment by Sonic0** [comment]
Hi @PhracturedBlue, thanks for this issue.
You are right, the code ignores the presence of microseconds.  Sorry for the problem, I'm going to fix it when I'll review version 2.0 of the roccivic/cron-converter code.

**Comment by Sonic0** [comment]
@PhracturedBlue I found where the problem was and it will be fixed in the next release integrating #18. Would you be able to try the PR code and let me know if it works for you?

**Comment by Sonic0** [comment]
I think this issue can be closed by merging #18 into the main branch. Please open a new issue if similar problems arise.
